name: tourganiser
description: "Tournament organisation app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
